# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='markbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_name', models.CharField(max_length=100)),
                ('mark_url', models.URLField(unique=True)),
                ('create_time', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='markbookDIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(max_length=200, unique=True)),
                ('dir_info', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='markbook',
            name='mark_belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mark.markbookDIR'),
        ),
    ]
