# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0007_auto_20160407_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markbook',
            options={'verbose_name': '\u4e66\u7b7e', 'verbose_name_plural': '\u4e66\u7b7e'},
        ),
        migrations.AlterModelOptions(
            name='markbookdir',
            options={'ordering': ['dir_name'], 'verbose_name': '\u4e66\u7b7e\u5939', 'verbose_name_plural': '\u4e66\u7b7e\u5939'},
        ),
    ]
